1. Pisahkan antara variabel yang dapat digunakan dan variabel yang tidak dapat digunakan.

In [16]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

dpath = 'wbc.csv'
df = pd.read_csv(dpath)
df.head()

df=df[['id','diagnosis','radius_mean', 'texture_mean', 'area_mean', 'smoothness_mean','concavity_mean']]
df.head()

,id,diagnosis,radius_mean,texture_mean,area_mean,smoothness_mean,concavity_mean
0,842302,M,17.99,10.38,1001.0,0.11840,0.3001
1,842517,M,20.57,17.77,1326.0,0.08474,0.0869
2,84300903,M,19.69,21.25,1203.0,0.10960,0.1974
3,84348301,M,11.42,20.38,386.1,0.14250,0.2414
4,84358402,M,20.29,14.34,1297.0,0.10030,0.1980

2. Lakukan proses encoding pada kolom "diagnosis".

In [17]:

le = LabelEncoder() # membuat objek dari LabelEncoder
df['diagnosis'] = le.fit_transform(df['diagnosis']) # proses encoding

df.head()

,id,diagnosis,radius_mean,texture_mean,area_mean,smoothness_mean,concavity_mean
0,842302,1,17.99,10.38,1001.0,0.11840,0.3001
1,842517,1,20.57,17.77,1326.0,0.08474,0.0869
2,84300903,1,19.69,21.25,1203.0,0.10960,0.1974
3,84348301,1,11.42,20.38,386.1,0.14250,0.2414
4,84358402,1,20.29,14.34,1297.0,0.10030,0.1980

3. Lakukan proses standarisasi pada semua kolom yang memiliki nilai numerik.

In [18]:

std = StandardScaler()
df['id'] = std.fit_transform(df[['id']])
df['diagnosis'] = std.fit_transform(df[['diagnosis']])
df['radius_mean'] = std.fit_transform(df[['radius_mean']])
df['texture_mean'] = std.fit_transform(df[['texture_mean']])
df['area_mean'] = std.fit_transform(df[['area_mean']])
df['smoothness_mean'] = std.fit_transform(df[['smoothness_mean']])
df['concavity_mean'] = std.fit_transform(df[['concavity_mean']])

df.head()

,id,diagnosis,radius_mean,texture_mean,area_mean,smoothness_mean,concavity_mean
0,-0.236405,1.297676,1.097064,-2.073335,0.984375,1.568466,2.652874
1,-0.236403,1.297676,1.829821,-0.353632,1.908708,-0.826962,-0.023846
2,0.431741,1.297676,1.579888,0.456187,1.558884,0.942210,1.363478
3,0.432121,1.297676,-0.768909,0.253732,-0.764464,3.283553,1.915897
4,0.432201,1.297676,1.750297,-1.151816,1.826229,0.280372,1.371011